### ISSUE TITLE
Matchmaking rank percentiles

### ISSUE THREAD

**Issue by Chris92de** [openplanet-nl/tmio#58]
As suggested in the Openplanet Discord, it would be nice if players with 0 score in 3v3 Ranked matchmaking could be filtered out of the calculation for the Rank percentiles. 
I highly doubt that with Silver 3 and 1686 points I'm in the "top 1%" as TM.io might suggest.
![image](https://github.com/openplanet-nl/tmio/assets/5523125/3addfbe5-7c5b-445c-aa32-049bad95093d)

**Comment by davidbmaier** [comment]
As announced in the Discord server, we're now testing an update that determines the number of "active players" instead of comparing a player's rank with the lifetime playerbase, which should result in a lot more representative percentiles.
I'll close this for now, let us know on Discord if you've got feedback about the changes.
