### ISSUE TITLE
Support map upload activities

### ISSUE THREAD

**Issue by ArEyeses79** [openplanet-nl/tmio#73]
Currently it isn't possible to see the maps in a map upload activity on trackmania.io
(Since skin uploads are supported, I expect this is fairly simple to add. Although map uploads would need a link to the map's leaderboard as well as a download link)

**Comment by davidbmaier** [comment]
Implemented and deployed, see the [BASE MAPS activity](https://trackmania.io/#/clubs/54094/maps/339228) in [the Cupra club](https://trackmania.io/#/clubs/54094/activities) for example.

Note that there's some other stuff breaking at the moment due to Nadeo API issues, so players' display names are broken.
