### ISSUE TITLE
TOTD name formatting wrong

### ISSUE THREAD

**Issue by ezio416** [openplanet-nl/tmio#98]
Today's TOTD is called "ultima" but the site is displaying "utima". I don't see anything weird in the raw map string:

$f91u$f92l$f93t$fa4im$fa5a $fb7ft$fc8' m$fdai$fdbcr$feco$fedvert

https://trackmania.io/#/totd/leaderboard/f61846c8-1506-4100-aabf-be1cc518307b/UVZnVIIPbclDOJCJt4GXZhTSP9l

**Comment by codecat** [comment]
The formatting code from the API actually looks like this:
```$f92u$f93t$fa4im$fa5a $fb7ft$fc8' m$fdai$fdbcr$feco$fedvert```
Perhaps the name changed at some point but the API doesn't reflect this correctly everywhere?

**Comment by davidbmaier** [comment]
This is caused by Nadeo's API occasionally returning an older version of the map that contained that typo - and tm.io unfortunately initially got the older version in the initial request that filled the cache. Since tm.io is caching that kind of information, it'll fix itself after the cache expires (24 hours after the request that filled it).
I assume this is due to the author reuploading the map using the same `mapUId` at some point, and the Nadeo API isn't always handling that case correctly.

For reference, the correct/new version:
> ultima ft' microvert.Map.Gbx
> 2024-04-16T04:58:28+00:00
> 16d90a59-ff7a-479b-b6f8-dcbbf323b308

And the old one:
> utima ft' microvert.Map.Gbx
> 2024-04-07T16:17:35+00:00
> 025c83df-7ec8-4704-98a0-c617ee9c9f27

We could manually clear the cache by restarting the site, but other than that tm.io is working as expected.

**Comment by codecat** [comment]
Thanks for checking that - I have restarted the site and it looks correct now.
